import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Layout from "@/components/Layout";
import proPic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/AnimatedText";
import { motion } from "framer-motion";
import { LinkArrow } from "@/components/Icon";
import HireJob from "@/components/HireJob";
import lightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg'

const inter = Inter({ subsets: ["latin"] });

// components/TypewriterComponent.js
import { useState, useEffect } from 'react';

const phrases = [
  'Goutam Sachdev',
  'Gen-AI Enthusiast',
  'ML Expert',
  'Python Developer',
  'AI Developer'
];

const TypewriterComponent = ({ className }) => {
  const [text, setText] = useState('');
  const [index, setIndex] = useState(0);
  const [charIndex, setCharIndex] = useState(0);
  const [isDeleting, setIsDeleting] = useState(false);

  useEffect(() => {
    const currentPhrase = phrases[index];
    const timeout = setTimeout(() => {
      setText(currentPhrase.substring(0, charIndex + (isDeleting ? -1 : 1)));
      if (!isDeleting && charIndex < currentPhrase.length) {
        setCharIndex(charIndex + 1);
      } else if (isDeleting && charIndex > 0) {
        setCharIndex(charIndex - 1);
      }
      if (charIndex === currentPhrase.length) {
        setIsDeleting(true);
      } else if (charIndex === 0 && isDeleting) {
        setIsDeleting(false);
        setIndex((index + 1) % phrases.length);
      }
    }, isDeleting ? 50 : 150);

    return () => clearTimeout(timeout);
  }, [charIndex, isDeleting, index]);

  return (
    <div className={`font-mono text-5xl flex space-x-3 ${className}`}>
      <h4>I am</h4>
      <strong className="bg-yellow-400 px-1">
        <p>{text}</p>
      </strong>
    </div>
  );
};



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center  text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 ">
          <div className="flex items-center  justify-between w-full">
            <div className="w-1/2">
              <Image
                src={proPic}
                alt="Profile Pic "
                className="w-full h-auto "
              />
            </div>
            <div className="w-1/2 flex flex-col itmes-center self-center">
             
            <div className="container mx-auto p-4 pl-10">
      <TypewriterComponent className="text-center" />
    </div>
              <h1>
                <AnimatedText
                  text="Unveiling innovation through code and algorithms"
                  className="!text-5xl"
                />
                <AnimatedText
                  text=" shaping tomorrow&apos;s reality, today and beyond"
                  className="!text-base  "
                />
              </h1>

              <motion.p
                className="my-2 text-sm font-light"
                initial={{ opacity: 0, x: 200, y: 100 }}
                animate={{ opacity: 1, x: 0, y: 0 }}
                transition={{ duration: 1 }}
              >
                I&apos;m passionate about writing code that brings ideas to life,
                creating practical solutions that captivate users and appeal to
                customers.
              </motion.p>
              <div className="flex items-center  self-start mt-2 justify-center justify-items-center  ">
                <Link
                  href="/GOUTAM-SACHDEV.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light  p-2.5 px-6
                rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark
                hover:dark:border-light hover:dark:bg-dark hover:dark:text-light
                "
                  download={true}
                >
                  
                  Resume <LinkArrow className={"w-6 ml-1  "} />
                </Link>
                <Link
                  className="ml-4 text-lg font-xl capitalize text-dark underline dark:text-light "
                  href="mailto:gksachdev46@gmail.com"
                  target={"_blank"}
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireJob />

        <div className="absolute right-8 bottom-8 inline-block w-24">

          <Image src={lightBulb} alt="!goutamSachdev" className="w-full h-auto" />
        </div>
      </main>
    </>
  );
}
